version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    build:
     shm_size: '4096mb'
    shm_size: '4096mb'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass secret --appendonly yes
    volumes:
      - ttt-redis-data:/data
    ports:
      - 6379:6379
volumes:
  ttt-redis-data:
  postgres-data: