version: '3.1'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./SQL/max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    shm_size: '4096mb'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save '' --requirepass secret"]
    ports:
      - 6379:6379

volumes:
  postgres-data:
