# Generated by Django 4.0.2 on 2022-02-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('total_games_played', models.IntegerField()),
            ],
            options={
                'db_table': 'Desks',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_uuid', models.UUIDField(db_column='game_uuid')),
                ('cur_state', models.BigIntegerField()),
                ('desk', models.BinaryField()),
            ],
            options={
                'db_table': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('looses', models.IntegerField(default=0)),
                ('player_uuid', models.UUIDField(db_column='player_uuid')),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BigIntegerField()),
                ('moves', models.BinaryField()),
                ('desk_id', models.ForeignKey(db_column='desk_id', on_delete=django.db.models.deletion.CASCADE, to='ttt_web.desks')),
            ],
            options={
                'db_table': 'States',
            },
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_players_name'),
        ),
        migrations.AddField(
            model_name='games',
            name='desk_size',
            field=models.ForeignKey(db_column='desk_size', on_delete=django.db.models.deletion.CASCADE, to='ttt_web.desks'),
        ),
        migrations.AddField(
            model_name='games',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='ttt_web.players'),
        ),
        migrations.AddConstraint(
            model_name='desks',
            constraint=models.UniqueConstraint(fields=('size',), name='unique_size'),
        ),
        migrations.AddConstraint(
            model_name='states',
            constraint=models.UniqueConstraint(fields=('desk_id', 'state'), name='unique_desk_id_states'),
        ),
        migrations.AddConstraint(
            model_name='games',
            constraint=models.UniqueConstraint(fields=('game_uuid',), name='unique_games_uuid'),
        ),
    ]
