# Generated by Django 4.0.2 on 2022-02-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='player_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='games',
            name='player_mark',
            field=models.CharField(default='x', max_length=2),
        ),
    ]
