# Generated by Django 4.0.2 on 2022-02-15 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='modified',
            field=models.DateTimeField(default=datetime.date(2022, 2, 15)),
        ),
    ]
