# Generated by Django 4.0.2 on 2022-02-15 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_games_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
