# Generated by Django 4.0.2 on 2022-02-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_games_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='next_player_code',
            field=models.IntegerField(default=1),
        ),
    ]
