# Generated by Django 4.2 on 2023-04-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_games_player1_path_games_player2_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='desk_size',
        ),
    ]
