# Generated by Django 4.0.5 on 2022-06-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_games_player1_path_games_player2_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='desk_size',
        ),
    ]
